version: '3'

services:
  invoker_gui:
    image: invoker_gui
    networks:
      - demo-network
    hostname: dummy
    container_name: invoker_gui
    build:
      context: ./invoker_gui
    volumes:
      - ./invoker_gui:/usr/src/app
    environment:
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
      - CAPIF_PORT=8080
      - EASY_RSA_HOSTNAME = easy-rsa
      - EASY_RSA_PORT=8083
      - REGISTER_HOSTNAME = register
      - REGISTER_PORT = 8084
      - CAPIF_PORT_HTTPS=443
      - CAPIF_CALLBACK_URL=host.docker.internal
      - CAPIF_CALLBACK_PORT=8086
    extra_hosts:
      - host.docker.internal:host-gateway
      - capifcore:host-gateway
      # - one_provider_gui:host-gateway
      - register:host-gateway
      - easy-rsa:host-gateway

networks:
  demo-network:
    external: true

