apiVersion: v1
kind: Service
metadata:
  name: capif-invoker-one
  labels:
    io.kompose.service: capif-invoker-one
  {{- include "capif-invoker-gui.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.invokerGui.type }}
  selector:
    io.kompose.service: capif-invoker-one
  {{- include "capif-invoker-gui.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.invokerGui.ports | toYaml | nindent 2 -}}